import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="nav">
          <div>
            <Link className="link" href="/">
              My App
            </Link>
          </div>

          <div>
            <Link className="link" href="/users">
              Users
            </Link>
            <Link className="link" href="/posts">
              Posts
            </Link>
            <Link className="link" href="/comments">
              Comments
            </Link>
            <Link className="link" href="/albums">
              Albums
            </Link>
            <Link className="link" href="/photos">
              Photos
            </Link>
            <Link className="link" href="/todos">
              Todos
            </Link>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
